# Workflow
# https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container
name: Container Workflow
on: [push, workflow_dispatch]
jobs:
  # job 1: running unit tests
  run-in-container:
    # every job has its own runner, basically a VM which is isolated from other jobs VM
    runs-on: ubuntu-latest
    container: 
      image: node:20.16.0-alpine3.20
    steps:
      # step 1: fetch code from repository to runner
      - name: Get code
        uses: actions/checkout@v4
      # step 2: verify node version
      - name: Node version
        run: node -v
      # step 3: Install project dependencies
      - name: Install dependencies
        run: npm ci
      # step 4: Run project lint
      - name: Run lint
        run: npm run lint
      # step 5: Run project tests
      - name: Run tests
        run: npm test