# Workflow
# by default jobs in workflow run in parallel, use needs to run it sequentially
name: Handle Issues
on: issues
jobs:
  # job 1: show context info
  output-info:
    # every job has its own runner, basically a VM which is isolated from other jobs VM
    runs-on: ubuntu-latest
    steps:
      # step 1: show event data
      - name: Output event details
        run: echo "${{ toJson(github.event) }}"

