# Workflow
name: Output Information
on: workflow_dispatch
env:
  USER_NAME: root
jobs:
  info:
    env: 
      JOB_ID: 1
    runs-on: ubuntu-latest
    steps:
    - name: Output job id
      run: echo $JOB_ID
    - name: Output Github context
      run: echo "${{ toJson(github) }}"
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Show user
        run: echo ${{ env.USER_NAME }}
      - name: Show job
        run: echo $JOB_ID
  # using reusable workflow - reusable-workflow.yml
  # https://docs.github.com/en/actions/sharing-automations/reusing-workflows
  deploy:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      echo-var: "Hello from caller"
  print-deploy-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy output
        run: echo ${{ needs.deploy.outputs.wf-status }}
