name: Reusable Deploy Workflow
# https://docs.github.com/en/actions/sharing-automations/reusing-workflows
on: 
  workflow_call:
    inputs:
      echo-var:
        description: the variable name that needs to be echoed in caller wf
        type: string
        required: false
        default: 'hello-world'
    outputs:
      wf-status: 
        description: The result of this reusable wf
        value: ${{ jobs.deploy.outputs.deploy-status }}

jobs:   
  display-input:
    runs-on: ubuntu-latest
    steps:
      - name: Output input
        run: echo ${{ inputs.echo-var }}
  deploy:
    outputs:
      deploy-status: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: echo "Deploying & Uploading"
      - name: Set result output
        id: set-result
        run: echo "step-result=reusable job/step success" >> $GITHUB_OUTPUT