name: Test Project
on: push
jobs:
    run-unit-tests:
        runs-on: ubuntu-latest
        steps:
            # step 1: fetch code from repository to runner
            - name: Get code
              uses: actions/checkout@v4
            # step 2: Install node js on runner
            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: '20.16.0'
            # step 3: verify node version
            - name: Node version
              run: node -v
            # step 4: Install project dependencies
            - name: Install dependencies
              run: npm ci
            # step 5: Run project tests
            - name: Run tests
              run: npm test


